#!/bin/sh

which vim || sudo pacman -S gvim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[ -f ~/.vimrc ] && mv ~/.vimrc ~/.vimrc.ori ; curl -fLo ~/.vimrc \
	https://raw.githubusercontent.com/bruhtus/dotfiles/master/.vimrc

vim -es -u vimrc -i NONE -c 'PlugInstall' -c 'qa'
